RDKCOM-4212: REFPLTB-2652 : dsm build issues with respect to new revision in...
Reason for change:
1. To get this https://github.com/rdkcentral/DSM/pull/48 change for kirkstone, updating the SRCREV
2. With the updated SRCREV faced below build errors
| /home/ssiras826/rpi4-kirk-Jun2-oe-fork/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/dsm/1.0-r0/git/src/datamodel/bridge/../adapters/container-runtime-adapter.hpp:26:10: fatal error: Dobby/DobbyProtocol.h: No such file or directory
|    26 | #include <Dobby/DobbyProtocol.h>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~
to resolve above build error , adding Dobby as dependency
Test Procedure: bitbake dsm
Risks: Low
Signed-off-by: Ssandhyarani <sirasanagandla.sandhyarani@ltts.com>
Priority: P1

(cherry picked from commit e82752fcb025913f48f60f5b41b97a09c6a43e97)
Change-Id: I258355c94b67d7de6bf441a8945bf39f6c7bd829