RDKCOM-4225: REFPLTB-2391 : Observed dobby compilation error in kirkstone
Reason for change: To fix the below error,
~/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/dobby/3.6.0+gitAUTOINC+effc78183e-r0/git/libocispec/src/read-file.c:17:10:
fatal error: config.h: No such file or directory
|    17 | #include <config.h>
|       |          ^~~~~~~~~~
| compilation terminated.
Test Procedure: dobby should be compiled successfully in kirkstone
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>
Priority: P1

(cherry picked from commit 4af7b33f32411a6782a33aeed57a268b3d1177ce)
Change-Id: I59c97bd43b964cc0554402408c0ede90c0d15369