RDKCOM-4533: RDKBDEV-2364 REFPLTB-2831 : Kirkstone build is broken in DSM
Reason for change: RDKB Kirkstone build is broken in DSM
build-rpi4-broadband-kirkstone/EXEC_0/build-raspberrypi4-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/dsm/1.0-r0/git/src/librbusprovider/table.h:46:23:
error: field 'table_name' has incomplete type 'const string' {aka 'const std::__cxx11::basic_string<char>'}
|    46 |     std::string const table_name;
Test Procedure: DSM component build should be successful.
                Full bitbake should be successful.
Risks: None
Signed-off-by: Pratheepa.P <pratheepa.p@ltts.com>
Priority: P1

(cherry picked from commit ddd01178418cc9c19291a37baaeb9d29091fbadf)
Change-Id: I20ba227ea22caa3ad701e157d850eed0ecd95e25