REFPLTB-2644 :  Set Proper DISTRO_CODENAME for kirkstone
Reason for change: Observed below errors,
ERROR: Nothing PROVIDES 'perl-native-runtime' (but
/home/kpandu549/jul25-kirkstone-rpi/meta-rdk-ext/recipes-connectivity/openssl/openssl_1.0.2o.bb,
virtual:native:/home/kpandu549/j
ul25-kirkstone-rpi/meta-rdk-ext/recipes-connectivity/openssl/openssl_1.0.2o.bb
DEPENDS on or otherwise requires it). Close matches:
  nativesdk-gcc-runtime
  nativesdk-go-runtime
  perl-native
ERROR: Required build target 'ccsp-cr' has no buildable providers.
Missing or unbuildable dependency chain was: ['ccsp-cr',
'ccsp-common-library', 'openssl', 'perl-native-runtime']
Test Procedure: Build the image successfully
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>
Change-Id: I9864b93442217784760cd20a03793548da22afe4